services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: film_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-film_db}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/test:/docker-entrypoint-initdb.d
    networks:
      - film_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # PGAdmin для управления БД
  pgadmin:
    image: dpage/pgadmin4
    container_name: film_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@film.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - film_network
    depends_on:
      - postgres
    restart: unless-stopped

  # Бэкенд приложение
  backend:
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: ghcr.io/infinity74853/film-backend:latest
    container_name: film_backend
    ports:
    - "3000:3000"
    environment:
      DATABASE_DRIVER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-film_db}
      LOGGER_TYPE: ${LOGGER_TYPE:-dev}
      NODE_ENV: ${NODE_ENV:-development}
    command: ["npm", "run", "start:prod"]
    networks:
      - film_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  
    restart: unless-stopped

  # Фронтенд
  frontend:
    build:
      context: ./frontend
    image: ghcr.io/infinity74853/film-frontend:latest
    container_name: film_frontend
    networks:
      - film_network
    volumes:
      - frontend_static:/usr/share/nginx/html
    restart: unless-stopped

  # Nginx сервер
  nginx:
    image: ghcr.io/infinity74853/film-nginx:latest
    container_name: film_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - frontend_static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - film_network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  frontend_static:

networks:
  film_network:
    driver: bridge