FROM node:22-alpine

WORKDIR /app

# Копируем ТОЛЬКО package файлы сначала
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем остальной код ПОСЛЕ установки зависимостей
COPY . .

EXPOSE 3000

# Простая команда без nodemon
CMD ["npm", "run", "start:dev"]