# nginx/Dockerfile
FROM nginx:alpine

# Копируем конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Создаем директорию для статики
RUN mkdir -p /usr/share/nginx/html

# Указываем что статика будет монтироваться через volume
VOLUME /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]