FROM nginx:alpine

# УДАЛЯЕМ дефолтные файлы nginx
RUN rm -rf /usr/share/nginx/html/*

# Копируем конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]