server {
    listen 80;
    listen 443 ssl;
    server_name _ igor-films.students.nomorepartiessbs.ru;

    # SSL сертификаты (только для HTTPS)
    ssl_certificate /etc/letsencrypt/live/igor-films.students.nomorepartiessbs.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/igor-films.students.nomorepartiessbs.ru/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }

    location /api/afisha/ {
        proxy_pass http://backend:3000/api/afisha/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /content/ {
        proxy_pass http://backend:3000/content/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
}